### ISSUE TITLE
Blockchain Node deployment Story

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tf_jukebox#4]
## Acceptance Criterias

user should be able to create block chains nodes 
the user will be asked how many nodes he want to deploy
and he will got a qr to scan to pay for those nodes

## tickets

- [x]  document how blockchain node is deployed on a container #19 
- [x]  create API endpoints https://github.com/threefoldtech/tf_jukebox/issues/18
- [x] create required SAL https://github.com/threefoldtech/tf_jukebox/issues/17
